import sys, dbm
from PyQt5 import QtWidgets
from PyQt5.QtCore import QDate 
from PyQt5.QtGui import QIcon

# Ui layouts generated by QtDesigner
from fWlayout import Ui_MainWindow
from fWlayout_config import Ui_Config
from fWlayout_stat import Ui_Stat 
from fWlayout_addTag import Ui_AddTag
from fWlayout_viewTag import Ui_ViewTag

# BEGIN CONFIG 

# TODO: Use config file module...
dbfilename = "freeWrite.db" 
dailygoal = 500 # TODO Front-end in words /\ Back-end in bytes 
debug = True

# END CONFIG

# BEGIN DIALOGS

# BEGIN CONFIG WINDOW

class ConfigDialog(QtWidgets.QDialog, Ui_Config):
    def __init__(self, *args, obj=None, **kwargs):
        suoer(ConfigDialog, self).__init__(*args, **kwargs)
        self.setupUi(self)

# END CONFIG WINDOW

# BEGIN STATS WINDOW

class StatsDialog(QtWidgets.QDialog, Ui_Stat):
    def __init__(self, *args, obj=None, **kwargs):
        suoer(StatsDialog, self).__init__(*args, **kwargs)
        self.setupUi(self)

# END STATS WINDOW

# BEGIN ADD TAG WINDOW

class AddTagDialog(QtWidgets.QDialog, Ui_AddTag):
    def __init__(self, *args, obj=None, **kwargs):
        suoer(AddTagDialog, self).__init__(*args, **kwargs)
        self.setupUi(self)

# END ADD TAG WINDOW

# BEGIN VIEW TAG WINDOW

class ViewTagDialog(QtWidgets.QDialog, Ui_ViewTag):
    def __init__(self, *args, obj=None, **kwargs):
        suoer(ViewTagDialog, self).__init__(*args, **kwargs)
        self.setupUi(self)

# END VIEW TAG WINDOW

# END DIAGOGUES

# BEGIN MAIN WINDOW 
# TODO  [ ] Context menu on main window 
#       `-->[ ] Slots for metadata (tagging) subsystem...
#          >[ ] Slot to open log stats child window...

class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    
    # BEGIN Constructor
    def __init__(self, *args, obj=None, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)
        self.setupUi(self)
        
        # BEGIN Pre-signal Staging 

        self.setWindowIcon(QIcon("icon.xpm")) # better icon format
        self.Today = QDate.currentDate() # Today initialized as QDate...icon.xpm
        self.calendarWidget.setMaximumDate(self.Today) #...to set max date...
        self.Today = self.Today.toString() #...then convert to string for later.
        self.statusBar().showMessage("Today is " + self.Today)
        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(dailygoal)
        self.readDate() #read Today to initialize widgets

        # END Pre-signal Staging

        # BEGIN SIGNALS
        
        # If the date selection changes, update widgets
        self.calendarWidget.selectionChanged.connect(self.readDate)
        # If return is pressed in the line editor, write to db
        self.lineEdit.returnPressed.connect(self.appendEntry)
        
        # END SIGNALS

    # END Constructor
    
    # BEGIN SLOTS

    # Update text browser and progress bar 
    def readDate(self): 
        selDate = self.calendarWidget.selectedDate().toString()
        if(debug): print("Read: " + selDate)
        selText = ""
        with dbm.open(dbfilename,'c') as db:
            try: selText = db[selDate]
            except: selText = b""
            finally: 
                self.textBrowser.setPlainText(str(selText,'utf-8'))
                if(len(selText) < dailygoal):
                    self.progressBar.setValue(len(selText))
                else:
                    self.progressBar.setValue(dailygoal)

    # Write to db (or not) then readDate(self)
    def appendEntry(self):
        selDate = self.calendarWidget.selectedDate().toString()
        if(selDate in self.Today):
            if(debug): print("Write: " + selDate)
            addText = self.lineEdit.text()
            with dbm.open(dbfilename,'c') as db:
                try: db[selDate] = db[selDate] + bytes(addText,'utf-8') + b"\n"
                except: db[selDate] = bytes(addText,'utf-8') + b"\n"
                finally: self.lineEdit.clear()
            self.readDate()
        elif(debug): 
            print("Prohibited: " + selDate + " is not Today " + self.Today)
        else: pass

    # END SLOTS

# END MAIN WINDOW
